"$schema" = 'https://starship.rs/config-schema.json'
palette = 'spacex_terrafab'

format = """
[░▒▓](accent)\
[  ](bg:accent fg:bg)\
$username\  
$directory\
[](fg:cyan bg:element)\
$git_branch\
$git_status\
[](fg:element bg:panel)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[ ](fg:panel)\
$character"""

[username]
show_always = true
style_user = "fg:bg bg:accent"
style_root = "fg:bg bg:accent"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:bg bg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:element"
format = '[[ $symbol $branch ](fg:cyan bg:element)]($style)'

[git_status]
style = "bg:element"
format = '[[($all_status$ahead_behind )](fg:cyan bg:element)]($style)'

[nodejs]
symbol = ""
style = "bg:panel"
format = '[[ $symbol ($version) ](fg:ice bg:panel)]($style)'

[bun]
symbol = ""
style = "bg:panel"
format = '[[ $symbol ($version) ](fg:ice bg:panel)]($style)'

[rust]
symbol = ""
style = "bg:panel"
format = '[[ $symbol ($version) ](fg:ice bg:panel)]($style)'

[golang]
symbol = ""
style = "bg:panel"
format = '[[ $symbol ($version) ](fg:ice bg:panel)]($style)'

[php]
symbol = ""
style = "bg:panel"
format = '[[ $symbol ($version) ](fg:ice bg:panel)]($style)'

[palettes.spacex_terrafab]
bg = "#060114"
panel = "#0d0820"
element = "#1f1a2c"
accent = "#757b9d"
ice = "#a1c4e4"
cyan = "#bad8ff"
text = "#d7dbe9"
