color_theme = "spacex-terrafab"
theme_background = true
truecolor = true
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
rounded_corners = true
terminal_sync = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "pid"
proc_colors = true
proc_gradient = true
proc_mem_bytes = true
proc_cpu_graphs = true
show_uptime = true
show_cpu_watts = true
check_temp = true
temp_scale = "celsius"
show_cpu_freq = true
mem_graphs = true
show_swap = true
show_disks = true
show_io_stat = true
io_mode = true
show_battery = true
show_battery_watts = true
log_level = "WARNING"
save_config_on_exit = true
